base:
  - ../../parts/wall_base/external/cut_stone_wall_base.
  - .external.stl
back:
  - ../../parts/arrow_slit/wall.external.standard/cut_stone_arrow_slit.
  - .external.standard.stl
x-min: 1
x-max: 4
y-min: 1
y-max: 4
result:
  - cut_stone_arrow_slit_wall.
  - .external.standard.stl
external: true
