base:
  - ../../parts/corner_base/external/cut_stone_corner_base.
  - .external.stl
back:
  - ../../parts/corner_back/external.standard/cut_stone_corner_back.
  - .external.standard.stl
min: 1
max: 4
result:
  - cut_stone_corner.
  - .external.stl
