base:
  - ../../parts/corridor_base/external/cut_stone_corridor_base.
  - .external.stl
back:
  - ../../parts/wall_back/external.standard/cut_stone_wall_back.
  - .external.standard.1.stl
front:
  - ../../parts/wall_back/external.standard/cut_stone_wall_back.
  - .external.standard.2.stl
x-min: 1
x-max: 4
y-min: 1
y-max: 4
result:
  - cut_stone_corridor.
  - .external.stl
external: true
